/*******************************************************************************
 * 
 * Copyright 2010 Alexandru Craciun, and individual contributors as indicated
 * by the @authors tag. 
 * 
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 3 of
 * the License, or (at your option) any later version.
 * 
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 ******************************************************************************/
/* Generated By:JJTree: Do not edit this line. ASTPercentExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.netxilia.spi.impl.formula.parser;

import org.netxilia.api.formula.IFormulaContext;
import org.netxilia.api.formula.IFormulaRenderer;
import org.netxilia.api.value.ErrorValue;
import org.netxilia.api.value.ErrorValueType;
import org.netxilia.api.value.GenericValueType;
import org.netxilia.api.value.IGenericValue;
import org.netxilia.api.value.NumberValue;

/**
 * An AST node representing an expression followed by one or more '%' symbols.
 */
public class ASTPercentExpression extends ASTBaseNode {
	private String name;

	public ASTPercentExpression(int id) {
		super(id);
		name = "Percent";
	}

	public ASTPercentExpression(FormulaParser p, int id) {
		super(p, id);
		name = "Percent";
	}

	@Override
	public IGenericValue eval(IFormulaContext context) {
		ASTBaseNode nLeft = (ASTBaseNode) jjtGetChild(0);
		ASTBaseNode nRight = (ASTBaseNode) jjtGetChild(1);

		IGenericValue gvValue = nLeft.eval(context);
		IGenericValue gvCount = nRight.eval(context);

		if (gvValue.getValueType() == GenericValueType.ERROR) {
			return gvValue;
		}

		Double val = gvValue.getNumberValue();
		Double count = gvCount.getNumberValue();

		if ((val == null) || (count == null)) {
			return new ErrorValue(ErrorValueType.VALUE);
		}

		return new NumberValue(Double.valueOf(val.doubleValue() * Math.pow(0.01d, count.doubleValue())));
	}

	@Override
	public String text(IFormulaRenderer context) {
		ASTBaseNode nLeft = (ASTBaseNode) jjtGetChild(0);
		ASTBaseNode nRight = (ASTBaseNode) jjtGetChild(1);

		StringBuilder sb = new StringBuilder();
		sb.append(nLeft.text(context));
		sb.append(nRight.text(context));
		return sb.toString();
	}

	@Override
	public String toString(String prefix, IFormulaContext context, IFormulaRenderer renderer) {
		return prefix + name + ":" + text(renderer) + " = " + eval(context);
	}
}
/* JavaCC - OriginalChecksum=8673eecb2b5ed28b51e1264792c6b705 (do not edit this line) */
