/*******************************************************************************
 * 
 * Copyright 2010 Alexandru Craciun, and individual contributors as indicated
 * by the @authors tag. 
 * 
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 3 of
 * the License, or (at your option) any later version.
 * 
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 ******************************************************************************/
/* Generated By:JJTree: Do not edit this line. ASTNxBoolean.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.netxilia.spi.impl.formula.parser;

import org.netxilia.api.formula.IFormulaContext;
import org.netxilia.api.formula.IFormulaRenderer;
import org.netxilia.api.value.BooleanValue;
import org.netxilia.api.value.IGenericValue;

/**
 * An AST node holding a parsed boolean.
 */
public class ASTPrimitiveBoolean extends ASTBaseNode {
	private BooleanValue bool;

	public ASTPrimitiveBoolean(int id) {
		super(id);
	}

	public ASTPrimitiveBoolean(FormulaParser p, int id) {
		super(p, id);
	}

	public void setBoolean(Boolean value) {
		this.bool = new BooleanValue(value);
	}

	@Override
	public IGenericValue eval(IFormulaContext context) {
		return bool;
	}

	@Override
	public String text(IFormulaRenderer context) {
		return bool.getStringValue();
	}

	@Override
	public String toString() {
		return "PrimitiveBoolean[" + bool + "]";
	}
}
/* JavaCC - OriginalChecksum=4eb0aa581641730422dc793babe9bb9a (do not edit this line) */
